config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :sharks do
    resources :posts
  end
  # Defines the root path route ("/")
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :shark
end

app/models/shark.rb
class Shark < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :facts, presence: true
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: 'ikush', password: 'shark', except: %i[index show]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :get_shark

  def create
    @post = @shark.posts.create(post_params)
  end

  def destroy
    @post = @shark.posts.find(params[:id])
    @post.destroy
  end

  private

  def get_shark
    @shark = Shark.find(params[:shark_id])
  end

  def post_params
    params.require(:post).permit(:body, :shark_id)
  end
end

app/controllers/sharks_controller.rb
class SharksController < ApplicationController
  before_action :set_shark, only: %i[ show edit update destroy ]

  # GET /sharks or /sharks.json
  def index
    @sharks = Shark.all
  end

  # GET /sharks/1 or /sharks/1.json
  def show
  end

  # GET /sharks/new
  def new
    @shark = Shark.new
  end

  # GET /sharks/1/edit
  def edit
  end

  # POST /sharks or /sharks.json
  def create
    @shark = Shark.new(shark_params)

    respond_to do |format|
      if @shark.save
        format.html { redirect_to shark_url(@shark), notice: "Shark was successfully created." }
        format.json { render :show, status: :created, location: @shark }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sharks/1 or /sharks/1.json
  def update
    respond_to do |format|
      if @shark.update(shark_params)
        format.html { redirect_to shark_url(@shark), notice: "Shark was successfully updated." }
        format.json { render :show, status: :ok, location: @shark }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sharks/1 or /sharks/1.json
  def destroy
    @shark.destroy

    respond_to do |format|
      format.html { redirect_to sharks_url, notice: "Shark was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shark
      @shark = Shark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shark_params
      params.require(:shark).permit(:name, :facts)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sharks_helper.rb
module SharksHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Want to Learn About Sharks?</h1>
        <p>Are you ready to learn about sharks?</p>
        <br>
        <p>
            <%= button_to 'Get Shark Info', sharks_path, :method => :get,  :class => "btn btn-primary btn-lg"%>
        </p>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <h3>Not all sharks are alike</h3>
            <p>Though some are dangerous, sharks generally do not attack humans. Out of the 500 species known to researchers, only 30 have been known to attack humans.
            </p>
        </div>
        <div class="col-lg-6">
            <h3>Sharks are ancient</h3>
            <p>There is evidence to suggest that sharks lived up to 400 million years ago.
            </p>
        </div>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark navbar-static-top navbar-expand-md">
    <div class="container">
        <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> 
            <span class="sr-only">Toggle navigation</span>
        </button>  <%= link_to "Everything Sharks", root_path, class: 'navbar-brand' %>
        <%# might be in the burger menu?  %>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav mr-auto">
            <li class='nav-item'><%= link_to 'Home', home_index_path, class: 'nav-link' %></li>
            <li class='nav-item'><%= link_to 'Sharks', sharks_path, class: 'nav-link' %></li>  
            <%# TODO: Check here for bug?  </li> %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "About Sharks" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "About Sharks" %>">  
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%# Specifies valid sources for JS. Part of Content Security Policy. %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# 
      Changing from javascript_include_tag to the below will help us work with the js in /packs 
      rather than the default asset pipeline 
    %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'%>
  </head>

  <body>
  <header>
    <%= render 'layouts/navigation' %>
  </header>
  <main role="main">
    <%= content_for?(:content) ? yield(:content) : yield %>
  </main>
  </body>
</html>

app/views/layouts/sharks.html.erb
<% content_for :content do %>
<div class="jumbotron text-center">
        <h1>Shark Info</h1>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <p>
                <%# content from the shark views come here %>
                    <%= yield %>
                </p>
            </div>
            <div class="col-lg-6">
                <p>

                    <div class="caption">You can always count on some sharks to be friendly and welcoming!</div>
                    <img src="https://assets.digitalocean.com/articles/docker_node_image/sammy.png" alt="Sammy the Shark">
                </p>

            </div>
        </div>
    </div>
<% end %>
<%= render template: 'layouts/application' %>

app/views/sharks/_all.html.erb
<% for post in @shark.posts %>
    <ul>
        <li class="post">
            <%= post.body %>
            <%# controller here refers to Stimulus controllers %>
            <%= button_tag "Remove Post", data: { controller: "posts", action: "posts#remove" } %>
            <%= button_tag "Upvote Post", data: { controller: "posts", action: "posts#upvote" } %>
        </li>
    </ul>
<%end%>

app/views/sharks/_form.html.erb
<%= form_with(model: shark) do |form| %>
  <% if shark.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shark.errors.count, "error") %> prohibited this shark from being saved:</h2>

      <ul>
        <% shark.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :facts, style: "display: block" %>
    <%= form.text_area :facts %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sharks/_posts.html.erb
 <div data-controller="posts">
    <%= form_with model: [@shark, @shark.posts.build], data: { action: "posts#addBody" } do |form| %>
        <%= form.text_area :body, data: { target: 'posts.body' }, placeholder: "Your post here" %>
        <br>
        <%= form.submit %>
    <% end %>
    <ul data-posts-target="add">
    </ul>
</div>

app/views/sharks/_shark.html.erb
<div id="<%= dom_id shark %>">
  <p>
    <strong>Name:</strong>
    <%= shark.name %>
  </p>

  <p>
    <strong>Facts:</strong>
    <%= shark.facts %>
  </p>
  <h2>Posts</h2>
  <%= render 'sharks/posts' %>

</div>

app/views/sharks/edit.html.erb
<h1>Editing shark</h1>

<%= render "form", shark: @shark %>

<br>

<div>
  <%= link_to "Show this shark", @shark, :class => "btn btn-primary btn-sm" %> <%= link_to "Back to sharks", sharks_path, :class => "btn btn-primary btn-sm" %>
</div>

app/views/sharks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sharks</h1>

<div id="sharks">
  <tbody>
    <% @sharks.each do |shark| %>
      <tr>
        <td><%= shark.name %></td>
        <td><%= shark.facts %></td>
        <td><%= button_to 'Show', shark_path(:id => shark.id), :method => :get %></td>
        <td><%= button_to 'Edit', edit_shark_path(:id => shark.id), :method => :get %></td>
        <td><%= button_to 'Destroy', shark_path(:id => shark.id), :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</div>

<%= link_to "New shark", new_shark_path, :class => "btn btn-primary btn-sm" %> 
<%= link_to 'Home', home_index_path, :class => "btn btn-primary btn-sm" %>

app/views/sharks/new.html.erb
<h1>New shark</h1>

<%= render "form", shark: @shark %>

<br>

<div>
  <%= link_to "Back to sharks", sharks_path, :class => "btn btn-primary btn-sm" %>
</div>

app/views/sharks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shark %>

<div>
  <%= link_to "Edit this shark", edit_shark_path(@shark), :class => "btn btn-primary btn-sm" %> <%= link_to "Back to sharks", sharks_path, :class => "btn btn-primary btn-sm" %>

  <div data-controller="posts">
    <button data-action="posts#showAll"> Show Older Posts </button>
    <div data-posts-target="show" style="visibility: hidden">
      <%= render 'sharks/all'%>
    </div>
  </div>

  <%= button_to "Destroy this shark", @shark, method: :delete %>
</div>